# Generated by Django 2.1.3 on 2019-01-25 00:10

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190125_0800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.RemoveField(
            model_name='article',
            name='create_time',
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor.models.UEditorField(verbose_name='文章内容'),
        ),
        migrations.AlterModelTable(
            name='article',
            table=None,
        ),
    ]
